[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "ALLOW-FROM https://trello.com"
  Content-Security-Policy = "frame-ancestors https://trello.com"
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
